language: cpp
compiler: gcc
dist: trusty

before_install:
# C++11
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
# C++11
- sudo apt-get install -qq g++-5

script:
- qmake ponyprog.pro -r -spec linux-g++-64 CONFIG+=debug QMAKE_CXX=g++-5 QMAKE_LINK=g++-5
- make

